import {test} from 'node:test';import assert from 'node:assert/strict';
import reservations from '../api/reservations.js';import adminAPI from '../api/admin.js';
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SECRET_KEY='sb_secret_test_only';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test_only';process.env.HOTEL_ID='tico-pousada';
const fetchOriginal=global.fetch;const response=value=>({ok:true,text:async()=>JSON.stringify(value),json:async()=>value});
function res(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};}
const request={name:'Teste',phone:'12999999999',email:'',checkin:'2099-01-01',checkout:'2099-01-03',adults:2,children:0,consent:true,notes:'',idempotency:'00000000-0000-4000-8000-000000000001'};
test('API falha de forma explícita quando banco não configurado',async()=>{const old=process.env.SUPABASE_URL;delete process.env.SUPABASE_URL;const out=res();await reservations({method:'GET',query:{}},out);assert.equal(out.code,503);assert.match(out.data.error,/configurado/);process.env.SUPABASE_URL=old;});
test('admin nega acesso sem autenticação antes de acessar dados',async()=>{global.fetch=()=>{throw new Error('Should not fetch');};const out=res();await adminAPI({method:'GET',headers:{}},out);assert.equal(out.code,401);global.fetch=fetchOriginal;});
test('admin de outra pousada é bloqueado',async()=>{global.fetch=async url=>url.includes('/auth/')?response({id:'some-user'}):response([]);const out=res();await adminAPI({method:'GET',headers:{authorization:'Bearer jwt-test'}},out);assert.equal(out.code,403);global.fetch=fetchOriginal;});
test('POST impede requisição de outra origem',async()=>{const out=res();await reservations({method:'POST',headers:{origin:'https://outro.test',host:'pousada.test'},body:request},out);assert.equal(out.code,403);});
test('preço e pousada vêm do servidor, não do visitante',async()=>{const calls=[];global.fetch=async(url,options)=>{calls.push({url,options});if(url.includes('hotel_limit'))return response(true);if(url.includes('hotel_create_request'))return response({id:'protocol',status:'pending',estimated_cents:80000});return response([{name:'Ti.co',whatsapp:'5512996182586'}]);};const out=res();await reservations({method:'POST',headers:{origin:'https://pousada.test',host:'pousada.test'},body:{...request,hotel_id:'another',estimated_cents:1,status:'confirmed'}},out);assert.equal(out.code,201);assert.equal(out.data.status,'pending');const payload=JSON.parse(calls.find(c=>c.url.includes('hotel_create_request')).options.body);assert.equal(payload.p_hotel,'tico-pousada');assert.equal(payload.p_data.estimated_cents,undefined);assert.equal(payload.p_data.status,undefined);assert.ok(!JSON.stringify(out.data).includes('sb_secret'));assert.ok(calls.every(c=>!c.options.headers.Authorization));global.fetch=fetchOriginal;});
test('limite persistente nega cadastro excedente sem salvar pedido',async()=>{const calls=[];global.fetch=async(url)=>{calls.push(url);return response(false);};const out=res();await reservations({method:'POST',headers:{origin:'https://pousada.test',host:'pousada.test'},body:request},out);assert.equal(out.code,429);assert.equal(calls.length,1);global.fetch=fetchOriginal;});
test('busca não retorna dados de hóspedes nem chaves',async()=>{global.fetch=async url=>url.includes('hotel_search')?response([{id:'room',name:'Suíte',capacity:2,total_cents:50000}]):response([{name:'Ti.co',whatsapp:'5512996182586'}]);const out=res();await reservations({method:'GET',query:{checkin:'2099-01-01',checkout:'2099-01-03',guests:'2'}},out);assert.equal(out.code,200);assert.ok(out.data.rooms.length);assert.equal(out.data.requests,undefined);global.fetch=fetchOriginal;});
test('grupo valida unidades e usa criação atômica sem confiar no preço do navegador',async()=>{const calls=[];global.fetch=async(url,opts)=>{calls.push({url,opts});if(url.includes('hotel_limit'))return response(true);if(url.includes('hotel_create_group_request'))return response({id:request.idempotency,requests:[{id:'a'},{id:'b'}]});return response([{name:'Ti.co',whatsapp:'5512996182586'}]);};const out=res();await reservations({method:'POST',headers:{origin:'https://pousada.test',host:'pousada.test'},body:{...request,coupon:' visita ',units:[{adults:2,children:1,ages:[4],room_id:null,total_cents:1},{adults:1,children:0,ages:[],room_id:null}]}},out);assert.equal(out.code,201);const payload=JSON.parse(calls.find(c=>c.url.includes('hotel_create_group_request')).opts.body);assert.equal(payload.p_data.coupon,'VISITA');assert.equal(payload.p_data.units.length,2);assert.equal(payload.p_data.units[0].total_cents,undefined);global.fetch=fetchOriginal;});
test('grupo rejeita quarto repetido e idades ausentes antes de consultar banco',async()=>{global.fetch=()=>{throw Error('Não deve acessar banco');};for(const units of [[{adults:2,children:0,ages:[],room_id:request.idempotency},{adults:1,children:0,ages:[],room_id:request.idempotency}],[{adults:2,children:1,ages:[],room_id:null}],Array.from({length:6},()=>({adults:2,children:0,ages:[]}))]){const out=res();await reservations({method:'POST',headers:{origin:'https://pousada.test',host:'pousada.test'},body:{...request,units}},out);assert.equal(out.code,400);}global.fetch=fetchOriginal;});
