import {createHmac} from 'node:crypto';
import {AppError} from './validation.js';
export function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY,publicKey=process.env.SUPABASE_PUBLISHABLE_KEY,hotel=process.env.HOTEL_ID;if(!url||!key||!publicKey||!hotel)throw new AppError('O cadastro online ainda está sendo configurado. Entre em contato com a pousada.',503);return {url:url.replace(/\/$/,''),key,publicKey,hotel};}
export async function db(path,options={}){const c=config();const r=await fetch(`${c.url}/rest/v1/${path}`,{...options,headers:{apikey:c.key,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(12000)});const raw=await r.text();const data=raw?JSON.parse(raw):null;if(!r.ok){if(data?.code==='23P01')throw new AppError('Este quarto já está ocupado nesse período. Atualize as opções.',409);if(data?.code==='22023')throw new AppError('O quarto ou pedido não está disponível. Atualize e tente novamente.',409);throw new AppError('Não foi possível salvar. Tente novamente em instantes.',502);}return data;}
export const rpc=(name,args)=>db(`rpc/${name}`,{method:'POST',body:JSON.stringify(args)});
export function send(res,status,data){res.setHeader('Cache-Control','no-store');return res.status(status).json(data);}
export function body(req){if(!req.body||typeof req.body!=='object'||Array.isArray(req.body)||JSON.stringify(req.body).length>10000)throw new AppError('Dados inválidos.');return req.body;}
export function sameOrigin(req){const origin=req.headers.origin;const host=req.headers['x-forwarded-host']||req.headers.host;if(!origin||new URL(origin).host!==host)throw new AppError('Origem inválida.',403);}
export async function admin(req){const c=config(),token=(req.headers.authorization||'').match(/^Bearer ([A-Za-z0-9._-]+)$/)?.[1];if(!token)throw new AppError('Entre no painel.',401);const r=await fetch(`${c.url}/auth/v1/user`,{headers:{apikey:c.publicKey,Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(10000)});const user=await r.json();if(!r.ok||!user.id)throw new AppError('Sessão expirada. Entre novamente.',401);const rows=await db(`hotel_admins?hotel_id=eq.${encodeURIComponent(c.hotel)}&user_id=eq.${encodeURIComponent(user.id)}&select=user_id`);if(!rows.length)throw new AppError('Você não tem acesso a esta pousada.',403);return user;}
export async function limit(req){const c=config(),ip=String(req.headers['x-vercel-forwarded-for']||req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();const hash=createHmac('sha256',c.key).update(`${c.hotel}:${ip}`).digest('hex');if(!await rpc('hotel_limit',{p_key:hash}))throw new AppError('Muitas solicitações. Tente novamente mais tarde.',429);}
export function route(fn){return async(req,res)=>{try{await fn(req,res);}catch(e){send(res,e.status||500,{error:e.status?e.message:'O serviço está temporariamente indisponível. Tente novamente.'});}};}
